# Generated by Django 5.2.7 on 2025-11-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="主机名"
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="IP地址")),
                ("disk", models.CharField(max_length=255, null=True)),
                ("mem", models.CharField(max_length=255, null=True)),
                ("cpu", models.CharField(max_length=255, null=True)),
                ("desc", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
